### PR TITLE
Saves default values to the database

### PR DESCRIPTION
**Pull request by ebarendt**
@matthuhiggins

### CODE REVIEW

**Comment by matthuhiggins** [comment]
Won't this always cause defaults to be written to the database, even if they didn't change? In the test case, if you read an object from the database with status:closed, and then call save, won't that save open to the database?

**Comment by ebarendt** [comment]
Fixed.

**Comment by matthuhiggins** [comment]
Not quite right, it seems!

When the object is initialized, add the default values to attributes. This will cause them to be dirty on write. Never reference the default values besides this one case.

**Comment by ebarendt** [comment]
> When the object is initialized, add the default values to attributes
That already happens: https://github.com/data-axle/superstore/blob/master/lib/superstore/core.rb#L12

**Comment by ebarendt** [comment]
Incorrectly.. I can use the write_attribute method.

**Comment by matthuhiggins** [comment]
:+1:

**Pull request merged**
