### PR TITLE
Support both Rails 5.2 and Rails 5.1

### PR DESCRIPTION
**Pull request by matthuhiggins**

### CODE REVIEW

**Comment by malept** [comment]
Perhaps CI should run on both Rails 5.1 and 5.2?

**Comment by matthuhiggins** [comment]
Agree

**Comment by malept** [comment]
Pull request for CI: https://github.com/data-axle/superstore/pull/45

Also, it appears that there is a couple failing tests related to timestamps introduced by this PR? See: https://travis-ci.org/data-axle/superstore/builds/495274916#L570

**Comment by matthuhiggins** [comment]
Those look like the classic `timezone` + `assert_equal` issue. I think new behavior is better and the test simply needs a fix.

**Pull request merged**
