### PR TITLE
Show how explicit ID can work

### PR DESCRIPTION
**Pull request by matthuhiggins**

### CODE REVIEW

**Comment by j1wilmot** [comment]
🤔Interesting. Thanks for demonstrating this. I'll try to pull this thread.

**Comment by matthuhiggins** [comment]
@j1wilmot Any notes on where you landed?

**Comment by j1wilmot** [comment]
I think this approach should work, but I've gotten bogged down by some version commit test failures in content system which has prevented me from pushing it all the way through. I'm taking a fresh look at that today.

One issue that came up is attribute ordering. Previously Id would be first because it was declared first. 
https://github.com/data-axle/superstore/compare/explicit-id-declaration#diff-a9549b7ebfec26924147933af4bcddd3L30

**Comment by matthuhiggins** [comment]
I'm unsure what you mean by ordering. Our UI order is controlled by other means. You can put ID declaration at the top of the attributes file if it really matters.

**Comment by matthuhiggins** [comment]
Can others help?

**Comment by j1wilmot** [comment]
[This test](https://github.com/data-axle/content_system/blob/master/test/presenters/place_fields/contacts_presenter_test.rb#L33-L38) fails because it expects id to come before created at. Putting ID as a first attribute in the attributes list doesn't work because created_at is automatically created. This probably isn't a big deal in the bigger picture.

The root of much suffering here was this [line](https://github.com/data-axle/content_system/blob/master/app/models/contact/email.rb#L3). Assigning the parent class a second time makes a bunch of the tests fail with the changes I was making. Removing the inheritance in this line fixes a bunch of the weird test failures I've been seeing.

[This](https://github.com/data-axle/superstore/compare/remove-id?expand=1) should get us close.

**Comment by matthuhiggins** [comment]
It's good that the test fails. Order matters. `popover_attributes` should be in charge of ordering the attributes though.

**Pull request closed without merging**
